### ISSUE TITLE
ImportError: No module named rotate_utils

### ISSUE THREAD

**Issue by Lunabig** [anilbatra2185/road_connectivity#1]
If you don't mind, may I ask the question: have you update all the code or do I do something wrong? I try:python road_dataset.py

**Comment by anilbatra2185** [comment]
Hi @Lunabig, I have updated the dataset file along with usage. Let me know for any issues.

**Comment by Lunabig** [comment]
Hi, @anilbatra2185 ,sorry to interrupt, I got some issues to download the dataset, could you send me a link to download the spacenet dataset from google cloud or baiducloud, I am awared that the dataset is too large, could you please send me the label at least?

**Comment by anilbatra2185** [comment]
Hi @Lunabig , I would request you to please refer to official link to download the dataset from AWS. Link: https://spacenetchallenge.github.io/datasets/spacenetRoads-summary.html

I would request you to please create a new issue, if there is any challenge in Spacenet data processing.
