### ISSUE TITLE
runtimeerror: input and target batch or spatial sizes don't match:target [16 * 256 * 3],input [16*37*256*256]

### ISSUE THREAD

**Issue by gengkai258** [anilbatra2185/road_connectivity#11]
CUDA_VISIBLE_DEVICES=0,1 python train_mtl.py --config config.json --dataset deepglobe --model_name "LinkNet34MTL" --exp dg_stak_mtl

**Comment by anilbatra2185** [comment]
As LinkNet34MTL does not perform multi-scale prediction, Request you to try 
`python train_mtl.py --config config.json --dataset deepglobe --model_name "LinkNet34MTL" --exp dg_stak_mtl --multi_scale_pred false`

**Comment by anilbatra2185** [comment]
@gengkai258 , there were some indentation issues in dataset and training file. I have updated them and request you to please try it again.

**Comment by gengkai258** [comment]
> @gengkai258 , there were some indentation issues in dataset and training file. I have updated them and request you to please try it again.

Thank you very much !  It worked!

**Comment by anilbatra2185** [comment]
Cool. So, I am closing the issue for now.
