### ISSUE TITLE
AWS account expired.how to download spacenet data?

### ISSUE THREAD

**Issue by ucalyptus** [anilbatra2185/road_connectivity#12]
Is there any other way to download the spacenet 3 data?

**Comment by anilbatra2185** [comment]
@ucalyptus, I do not know about alternatives to download the dataset.

**Comment by ucalyptus** [comment]
Ok

**Comment by ntelo007** [comment]
@ucalyptus you can download the Spacenet 3 datasets if you go to the Spacenet 5 challenge. Both datasets (3 and 5) are stored in a new AWS bucket.
