### ISSUE TITLE
AttributeError: 'MultiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by ntelo007** [anilbatra2185/road_connectivity#18]
Good evening,

when I am trying to start training the network, I get the following error:

  File "C:\Users\...\road_connectivity-master\data_utils\graph_utils.py", line 53,
in simplify_graph
    full_segments = np.row_stack([graph.node[s]["o"], ps, graph.node[e]["o"]])
AttributeError: 'MultiGraph' object has no attribute 'node'

**Comment by anilbatra2185** [comment]
Hi @ntelo007, can you please check the version of [networkx](https://networkx.github.io/) library and if it is different from 1.11 then I would request you to please try installing with version-1.11 and remove all other versions.
Please let me know, if it helps.

**Comment by ntelo007** [comment]
You were right, the version was higher. I downgraded it and that error went away. But unfortunately, this one showed up:

File "train_mtl.py", line 222, in train
    train_loss_iou += loss1.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by anilbatra2185** [comment]
> You were right, the version was higher. I downgraded it and that error
> went away. But unfortunately, this one showed up:
>
> File "train_mtl.py", line 222, in train
> train_loss_iou += loss1.data[0]
> IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert
> a 0-dim tensor to a Python number
>
> —

I think, this issue is related to new PyTorch version changes. So, I would
request you to please check PyTorch docs. For reference, the current issue
can be resolved using the simple following change.

train_loss_iou += loss1.data[0] ----> train_loss_iou += loss1.data

Thanks
Anil

**Comment by ntelo007** [comment]
You were right again, this was resolved. I am sorry to do that but another problem occurred! 

image, gt = self.random_crop(image, gt, self.crop_size)
UnboundLocalError: local variable 'image' referenced before assignment

It doesn't seem like a versioning problem.

**Comment by anilbatra2185** [comment]
@ntelo007 , the image data paths might be incorrect. Check line [69](https://github.com/anilbatra2185/road_connectivity/blob/master/road_dataset.py#L69) in dataset file.

**Comment by ntelo007** [comment]
Can you send me an example on how the train_crops.txt file should look like? (first 5 lines or so..) 
Probably the newline character messed up everything. (I am running your code on Windows)

**Comment by anilbatra2185** [comment]
Hi @ntelo007, train_crops.txt file should contain the name of crops without image extensions. Example -> 'RGB-PanSharpen_AOI_4_Shanghai_img219_0_0' for the first crop.

I am closing this issue, as main issue has been resolved. Please open a new issue, if you face some other challenges.

Thanks.

**Comment by ntelo007** [comment]
Would the following image file name affect the training?
instead of: 'RGB-PanSharpen_AOI_4_Shanghai_img219_0_0' 
just: '219_0_0'

**Comment by anilbatra2185** [comment]
@ntelo007 , I feel that just removing only one image might not make any difference.

**Comment by ntelo007** [comment]
I mean, is the name of the file really important? I am just keeping the final part (219_0_)0) of the name and not all the previous info ('RGB...'). I created my own pre-processing python script because I am running your code in Windows 10, and I can't use your shell script files.

**Comment by anilbatra2185** [comment]
@ntelo007, I don't think so that the name of file matters any thing in training. If you found some error, please let me know. However, dataloader expects the file name without any extensions. please verify according to your train/val text files.
