### ISSUE TITLE
how can we produce training dataset with DeepGlobe?

### ISSUE THREAD

**Issue by luoqianchina** [anilbatra2185/road_connectivity#19]
In the paper, I see you use linestring(this information is in the dataset SpaceNet ). However, There is no linestring datastruct in dataset Deepglobe(there are just two kinds of pictures binary gt pics and satelite pics). So how can we produce training dataset with DeepGlobe? Thank you very much!

**Comment by anilbatra2185** [comment]
Hi @luoqianchina, I request you to please refer paragraph in section 5.1 having title "DeepGlobe". Please create a new issue, if you see any other challenge.
