### ISSUE TITLE
NumbaWarnings and RuntimeWarnings / console log attaced

### ISSUE THREAD

**Issue by ntelo007** [anilbatra2185/road_connectivity#20]
Hi,

I get many NumbaWarnings and Runtime Erros, mainly for code written within the sknw.py, and then training fails. I hope you can find why this is happening by reading the attached log message that I get in my cmd.

[cmd_log.txt](https://github.com/anilbatra2185/road_connectivity/files/3874464/cmd_log.txt)

**Comment by anilbatra2185** [comment]
Hi @ntelo007, please confirm if you are using windows or Ubuntu OS. In my development, ubuntu OS was used.
Also, the issue described is in external github repo of "[sknw](https://github.com/Image-Py/sknw)" and my first guess is version of numba. I would suggest you to try lower version of numba.

I hope it helps.

Thanks.

**Comment by ntelo007** [comment]
@anilbatra2185 I am using Windows 10. I downgraded numba until the warnings were gone. Now, I resume training and I get a different error that is documented in the following file:
[cmd_log.txt](https://github.com/anilbatra2185/road_connectivity/files/3878595/cmd_log.txt)

Thank you for your time.

**Comment by anilbatra2185** [comment]
@ntelo007, Can you try to run the notebook by changing the dataset from Spacenet to Deepglobe. My guess is "sknw" might has some issues on windows. Is it possible for you to try it on Ubuntu quickly.

**Comment by ntelo007** [comment]
I am already running on DeepGlobe dataset. Running on Ubuntu is not an option at the moment. Do you have any other ideas in mind?

**Comment by anilbatra2185** [comment]
@ntelo007 , I would try first demo code of sknw (available on github) and fix for any issues.

**Comment by ntelo007** [comment]
> @ntelo007 , I would try first demo code of sknw (available on github) and fix for any issues.

Can you please upload your requirements.txt or send it here? It seems that the sknw package might indeed be the problem, but in order for your algorithm to run, you had specific packages installed that managed to cooperate with sknw.

**Comment by ntelo007** [comment]
I talked with the contributor of the sknw code. He updated his code, so you can fetch his file as well.

**Comment by anilbatra2185** [comment]
Closing this issue, as it is resolved now.
