### ISSUE TITLE
Spacenet Road Extraction Dataset

### ISSUE THREAD

**Issue by shicheng123moon** [anilbatra2185/road_connectivity#25]

**Comment by anilbatra2185** [comment]
@shicheng123moon, Thanks for showing interest in the work. I am sorry, as I do not have dataset saved locally. If it is not available on AWS, then I would request you to please create issue with Spacenet Team and if I found public link, I will share it.

**Comment by shicheng123moon** [comment]
Thank you so much! 
-- Shicheng Zu











At 2020-03-01 14:12:07, "Anil Batra" <notifications@github.com> wrote:

@shicheng123moon, Thanks for showing interest in the work. I am sorry, as I do not have dataset saved locally. If it is not available on AWS, then I would request you to please create issue with Spacenet Team and if I found public link, I will share it.
