### ISSUE TITLE
What type of the iou in the code is?

### ISSUE THREAD

**Issue by mathfinder** [anilbatra2185/road_connectivity#27]
Hi, There are two type of Road IOU in your paper IoU^r and IoU^a. What type of the iou in the code is?

**Comment by anilbatra2185** [comment]
Hi @mathfinder , the current code compute accurate road IoU i.e. IoU^a.

**Comment by anilbatra2185** [comment]
I have added the relaxed IoU metric function [link](https://github.com/anilbatra2185/road_connectivity/blob/master/utils/util.py#L281). Please create a new issue if you found any error in the function.

**Comment by neiheih** [comment]
I think relaxed IoU metric function may be not correct https://github.com/anilbatra2185/road_connectivity/blob/01e41662a43d9e289926ebd58eff4f6e14359ae4/utils/util.py#L290
It should be precision = rprecision_tp/(pred_positive+ 1e-12)
