### ISSUE TITLE
how to infer on the test set

### ISSUE THREAD

**Issue by kangkai98** [anilbatra2185/road_connectivity#34]
Thanks for your great work! I've trained the model successfully, and I want to use the model to infer on the test set and submit the predicted pictures on deepglobe website to evaluate. However, I doesn't find the infer code in it. Can you give me some advices?

**Comment by anilbatra2185** [comment]
Hi @kangkau, I would request you to write a code similar to [link](https://github.com/anilbatra2185/road_connectivity/blob/master/train_mtl.py#L295) and save each prediction as RGB image with appropriate labels.

Thanks
