### ISSUE TITLE
Question about SapceNet dataset processing

### ISSUE THREAD

**Issue by XiaoXiLe2023** [anilbatra2185/road_connectivity#5]
Hi,
  I tried your **Data Preparation** process to the step of **Split Datasets**. I did got the full folder with 2780 images. However, using your code, it came out 1999 images in train folder and 566 images in val folder. The result is different from '2213 images for training and 567 for testing' in your CVPR2019 essay. 
  Should the 566 images be used for testing? Should I pull some images out from train folder to make a val dataset? 
  I really want to use the same dataset with you to evaluate the performance of our network. 
  Thanks a lot!

**Comment by anilbatra2185** [comment]
The train file was missing Images from Khartoum city. I have updated the train.txt file and now I hope you should get 2213 images for training. However, val.txt has 567 entries. Request you to check if there is any corrupted image in your full folder which might happen during download or conversion from 11-bit to 8-bit.

**Comment by XiaoXiLe2023** [comment]
Thanks,this problem is solved.
