### ISSUE TITLE
split_data.sh: line 43:  /data/deepglobe/train.txt: No such file or directory split_data.sh: line 51:  /data/deepglobe/val.txt: No such file or directory

### ISSUE THREAD

**Issue by gengkai258** [anilbatra2185/road_connectivity#8]
I have put the deepglobe data in the right path:

--data/deepglobe/train   val.txt   train.txt
--data/deepglobe/train/_sat.jpg  _mask.png
  
but when I run:

bash split_data.sh /deepglobe/train /data/deepglobe _sat.jpg _mask.png

it still told me:   
split_data.sh: line 43:  /data/deepglobe/train.txt: No such file or directory
split_data.sh: line 51:  /data/deepglobe/val.txt: No such file or directory

This question has been solved when I use a deep path ! thank you ! you can delete this question~ because it is not a common problem

**Comment by gengkai258** [comment]
This question has been solved when I use a deep path ! thank you ! you can delete this question~ because it is not a common problem

> I have put the deepglobe data in the right path:
> 
> --data/deepglobe/train val.txt train.txt
> --data/deepglobe/train/_sat.jpg _mask.png
> 
> but when I run:
> 
> bash split_data.sh /deepglobe/train /data/deepglobe _sat.jpg _mask.png
> 
> it still told me:
> split_data.sh: line 43: /data/deepglobe/train.txt: No such file or directory
> split_data.sh: line 51: /data/deepglobe/val.txt: No such file or directory

This question has been solved when I use a deep path ! thank you ! you can delete this question~ because it is not a common problem

**Comment by gengkai258** [comment]
This question has been solved when I use a deep path ! thank you ! you can delete this question~ because it is not a common problem

> I have put the deepglobe data in the right path:
> 
> --data/deepglobe/train val.txt train.txt
> --data/deepglobe/train/_sat.jpg _mask.png
> 
> but when I run:
> 
> bash split_data.sh /deepglobe/train /data/deepglobe _sat.jpg _mask.png
> 
> it still told me:
> split_data.sh: line 43: /data/deepglobe/train.txt: No such file or directory
> split_data.sh: line 51: /data/deepglobe/val.txt: No such file or directory

This question has been solved when I use a deep path ! thank you ! you can delete this question~ because it is not a common problem

**Comment by anilbatra2185** [comment]
Thanks @gengkai258 for responding and based on your response I am closing this issue.
